INSERT INTO nomenclature (code, label) VALUES ('481', 'Acoustique et son');
INSERT INTO nomenclature (code, label) VALUES ('410', 'Agronomie, agriculture');
INSERT INTO nomenclature (code, label) VALUES ('421', 'Apprentissage, fouille de données, Big Data');
INSERT INTO nomenclature (code, label) VALUES ('580', 'Archéologie');
INSERT INTO nomenclature (code, label) VALUES ('572', 'Architecture, urbanisme, aménagement');
INSERT INTO nomenclature (code, label) VALUES ('330', 'Arts et sciences');
INSERT INTO nomenclature (code, label) VALUES ('511', 'Astrophysique');
INSERT INTO nomenclature (code, label) VALUES ('422', 'Automates, logique et jeux');
INSERT INTO nomenclature (code, label) VALUES ('221', 'Automatique');
INSERT INTO nomenclature (code, label) VALUES ('110', 'Bibliothèques');
INSERT INTO nomenclature (code, label) VALUES ('381', 'Biochimie et biogéochimie');
INSERT INTO nomenclature (code, label) VALUES ('532', 'Bioéthique');
INSERT INTO nomenclature (code, label) VALUES ('531', 'Bioinformatique');
INSERT INTO nomenclature (code, label) VALUES ('441', 'Bioinformatique');
INSERT INTO nomenclature (code, label) VALUES ('520', 'Biologie');
INSERT INTO nomenclature (code, label) VALUES ('529', 'Biologie animale');
INSERT INTO nomenclature (code, label) VALUES ('522', 'Biologie cellulaire');
INSERT INTO nomenclature (code, label) VALUES ('527', 'Biologie intégrative et Neurosciences');
INSERT INTO nomenclature (code, label) VALUES ('523', 'Biologie moléculaire');
INSERT INTO nomenclature (code, label) VALUES ('530', 'Biologie végétale');
INSERT INTO nomenclature (code, label) VALUES ('243', 'Biomatériaux');
INSERT INTO nomenclature (code, label) VALUES ('489', 'Biophysique');
INSERT INTO nomenclature (code, label) VALUES ('521', 'Biotechnologie, biologie de synthèse');
INSERT INTO nomenclature (code, label) VALUES ('560', 'Business, finance et management');
INSERT INTO nomenclature (code, label) VALUES ('423', 'Calcul scientifique, algorithmique');
INSERT INTO nomenclature (code, label) VALUES ('250', 'Caractérisation');
INSERT INTO nomenclature (code, label) VALUES ('389', 'Catalyse');
INSERT INTO nomenclature (code, label) VALUES ('380', 'Chimie');
INSERT INTO nomenclature (code, label) VALUES ('388', 'Chimie des matériaux');
INSERT INTO nomenclature (code, label) VALUES ('386', 'Chimie des substances naturelles');
INSERT INTO nomenclature (code, label) VALUES ('384', 'Chimie et sciences du vivant');
INSERT INTO nomenclature (code, label) VALUES ('382', 'Chimie inorganique');
INSERT INTO nomenclature (code, label) VALUES ('383', 'Chimie organique');
INSERT INTO nomenclature (code, label) VALUES ('385', 'Chimie radicalaire, physique');
INSERT INTO nomenclature (code, label) VALUES ('387', 'Chimie théorique et calculs');
INSERT INTO nomenclature (code, label) VALUES ('453', 'Climat et atmosphère');
INSERT INTO nomenclature (code, label) VALUES ('571', 'Communication, organisation, multimédia');
INSERT INTO nomenclature (code, label) VALUES ('249', 'Comportement mécanique');
INSERT INTO nomenclature (code, label) VALUES ('244', 'Composites');
INSERT INTO nomenclature (code, label) VALUES ('242', 'Couches minces, surfaces et interfaces');
INSERT INTO nomenclature (code, label) VALUES ('430', 'Cryptographie, sécurité des données');
INSERT INTO nomenclature (code, label) VALUES ('424', 'Décision et recherche opérationnelle');
INSERT INTO nomenclature (code, label) VALUES ('584', 'Démographie');
INSERT INTO nomenclature (code, label) VALUES ('561', 'Droit');
INSERT INTO nomenclature (code, label) VALUES ('588', 'Droit des données, du numérique, des connaissances');
INSERT INTO nomenclature (code, label) VALUES ('450', 'Ecologie et environnement');
INSERT INTO nomenclature (code, label) VALUES ('545', 'Economie de la santé');
INSERT INTO nomenclature (code, label) VALUES ('562', 'Economie et développement durables');
INSERT INTO nomenclature (code, label) VALUES ('483', 'Electromagnétisme, métamatériaux');
INSERT INTO nomenclature (code, label) VALUES ('180', 'Electronique');
INSERT INTO nomenclature (code, label) VALUES ('271', 'Eléments finis / Méthodes numériques');
INSERT INTO nomenclature (code, label) VALUES ('200', 'Energie');
INSERT INTO nomenclature (code, label) VALUES ('203', 'Energie nucléaire');
INSERT INTO nomenclature (code, label) VALUES ('202', 'Energies fossiles');
INSERT INTO nomenclature (code, label) VALUES ('201', 'Energies renouvelables');
INSERT INTO nomenclature (code, label) VALUES ('563', 'Entrepreunariat, gestion et marketing-management');
INSERT INTO nomenclature (code, label) VALUES ('582', 'Epistémologie');
INSERT INTO nomenclature (code, label) VALUES ('589', 'Ethique des sciences et des technologies');
INSERT INTO nomenclature (code, label) VALUES ('533', 'Evolution');
INSERT INTO nomenclature (code, label) VALUES ('223', 'Fiabilité, diagnostic, sécurité, maintenance des systèmes');
INSERT INTO nomenclature (code, label) VALUES ('564', 'Finance');
INSERT INTO nomenclature (code, label) VALUES ('524', 'Génétique, génomique');
INSERT INTO nomenclature (code, label) VALUES ('140', 'Génie civil et construction');
INSERT INTO nomenclature (code, label) VALUES ('340', 'Génie des procédés');
INSERT INTO nomenclature (code, label) VALUES ('160', 'Génie électrique');
INSERT INTO nomenclature (code, label) VALUES ('220', 'Génie industriel');
INSERT INTO nomenclature (code, label) VALUES ('270', 'Génie mécanique');
INSERT INTO nomenclature (code, label) VALUES ('245', 'Géomatériaux');
INSERT INTO nomenclature (code, label) VALUES ('275', 'Géomécanique');
INSERT INTO nomenclature (code, label) VALUES ('460', 'Géosciences');
INSERT INTO nomenclature (code, label) VALUES ('390', 'Hétérochimie');
INSERT INTO nomenclature (code, label) VALUES ('578', 'Histoire des STM');
INSERT INTO nomenclature (code, label) VALUES ('576', 'Humanités digitales');
INSERT INTO nomenclature (code, label) VALUES ('451', 'Hydrologie et eau');
INSERT INTO nomenclature (code, label) VALUES ('525', 'Immunologie, relation hôte pathogène, infections');
INSERT INTO nomenclature (code, label) VALUES ('420', 'Informatique');
INSERT INTO nomenclature (code, label) VALUES ('431', 'Informatique industrielle');
INSERT INTO nomenclature (code, label) VALUES ('432', 'Informatique médicale');
INSERT INTO nomenclature (code, label) VALUES ('433', 'Informatique quantique');
INSERT INTO nomenclature (code, label) VALUES ('541', 'Ingénierie de la santé');
INSERT INTO nomenclature (code, label) VALUES ('566', 'Innovation');
INSERT INTO nomenclature (code, label) VALUES ('546', 'Innovation en santé');
INSERT INTO nomenclature (code, label) VALUES ('544', 'Instrumentation médicale et bio-médicale');
INSERT INTO nomenclature (code, label) VALUES ('484', 'Instrumentation, capteurs, signal et mesures');
INSERT INTO nomenclature (code, label) VALUES ('425', 'Intelligence artificielle');
INSERT INTO nomenclature (code, label) VALUES ('426', 'Internet, web');
INSERT INTO nomenclature (code, label) VALUES ('577', 'Langues enseignement');
INSERT INTO nomenclature (code, label) VALUES ('434', 'Linguistique');
INSERT INTO nomenclature (code, label) VALUES ('435', 'Machines, architecture et systèmes d’exploitation');
INSERT INTO nomenclature (code, label) VALUES ('587', 'Management des connaissances scientifiques');
INSERT INTO nomenclature (code, label) VALUES ('247', 'Matériaux autres');
INSERT INTO nomenclature (code, label) VALUES ('248', 'Matériaux métalliques');
INSERT INTO nomenclature (code, label) VALUES ('350', 'Mathématiques et statistiques');
INSERT INTO nomenclature (code, label) VALUES ('485', 'Matière condensée');
INSERT INTO nomenclature (code, label) VALUES ('206', 'Matières premières et matériaux pour l’énergie');
INSERT INTO nomenclature (code, label) VALUES ('273', 'Mécanique des fluides');
INSERT INTO nomenclature (code, label) VALUES ('272', 'Mécanique des solides et des structures');
INSERT INTO nomenclature (code, label) VALUES ('276', 'Mécanique du vivant');
INSERT INTO nomenclature (code, label) VALUES ('274', 'Mécanique industrielle');
INSERT INTO nomenclature (code, label) VALUES ('526', 'Microbiologie et virologie');
INSERT INTO nomenclature (code, label) VALUES ('436', 'Multimédia');
INSERT INTO nomenclature (code, label) VALUES ('300', 'Nanotechnologies');
INSERT INTO nomenclature (code, label) VALUES ('452', 'Océanographie et paleoocéanographie');
INSERT INTO nomenclature (code, label) VALUES ('542', 'Oncologie, cancer');
INSERT INTO nomenclature (code, label) VALUES ('534', 'Pharmacologie, toxicologie');
INSERT INTO nomenclature (code, label) VALUES ('586', 'Philosophie');
INSERT INTO nomenclature (code, label) VALUES ('487', 'Photonique, optique et lasers');
INSERT INTO nomenclature (code, label) VALUES ('535', 'Physiologie');
INSERT INTO nomenclature (code, label) VALUES ('482', 'Physique des particules');
INSERT INTO nomenclature (code, label) VALUES ('480', 'Physique et ondes');
INSERT INTO nomenclature (code, label) VALUES ('488', 'Physique molle');
INSERT INTO nomenclature (code, label) VALUES ('391', 'Phytochimie');
INSERT INTO nomenclature (code, label) VALUES ('246', 'Polymères');
INSERT INTO nomenclature (code, label) VALUES ('251', 'Procédés');
INSERT INTO nomenclature (code, label) VALUES ('224', 'Production industrielle / Logistique');
INSERT INTO nomenclature (code, label) VALUES ('427', 'Programmation, logiciels, théorie des automates');
INSERT INTO nomenclature (code, label) VALUES ('241', 'Propriétés et traitement des matériaux');
INSERT INTO nomenclature (code, label) VALUES ('585', 'Psychologie');
INSERT INTO nomenclature (code, label) VALUES ('437', 'Puces / architecture, conception, programmation');
INSERT INTO nomenclature (code, label) VALUES ('321', 'Réseaux');
INSERT INTO nomenclature (code, label) VALUES ('320', 'Réseaux et télécoms');
INSERT INTO nomenclature (code, label) VALUES ('567', 'Ressources humaines');
INSERT INTO nomenclature (code, label) VALUES ('226', 'Robotique');
INSERT INTO nomenclature (code, label) VALUES ('400', 'Science des aliments');
INSERT INTO nomenclature (code, label) VALUES ('240', 'Science des matériaux');
INSERT INTO nomenclature (code, label) VALUES ('100', 'Science et Technologie STM  Général');
INSERT INTO nomenclature (code, label) VALUES ('392', 'Sciences analytiques chimiques');
INSERT INTO nomenclature (code, label) VALUES ('583', 'Sciences cognitives');
INSERT INTO nomenclature (code, label) VALUES ('579', 'Sciences de l’éducation et formation');
INSERT INTO nomenclature (code, label) VALUES ('540', 'Sciences de la santé');
INSERT INTO nomenclature (code, label) VALUES ('581', 'Sciences du langage,TAL');
INSERT INTO nomenclature (code, label) VALUES ('101', 'Sciences du vivant Général');
INSERT INTO nomenclature (code, label) VALUES ('548', 'Sciences médicales');
INSERT INTO nomenclature (code, label) VALUES ('547', 'Sciences pharmaceutiques');
INSERT INTO nomenclature (code, label) VALUES ('590', 'Sciences politiques');
INSERT INTO nomenclature (code, label) VALUES ('570', 'SHS');
INSERT INTO nomenclature (code, label) VALUES ('102', 'SHS Général');
INSERT INTO nomenclature (code, label) VALUES ('543', "SI et traitement de l'information pour la santé");
INSERT INTO nomenclature (code, label) VALUES ('428', 'SI, traitement données, communication');
INSERT INTO nomenclature (code, label) VALUES ('573', 'SIG et géographie');
INSERT INTO nomenclature (code, label) VALUES ('574', 'Sociologie et anthropologie');
INSERT INTO nomenclature (code, label) VALUES ('470', 'Spatiologie');
INSERT INTO nomenclature (code, label) VALUES ('360', 'Statistiques');
INSERT INTO nomenclature (code, label) VALUES ('204', "Stockage et distribution de l'énergie");
INSERT INTO nomenclature (code, label) VALUES ('536', 'Systématique, taxonomie');
INSERT INTO nomenclature (code, label) VALUES ('428', "Systèmes d'information, traitement données, communication");
INSERT INTO nomenclature (code, label) VALUES ('225', 'Systèmes homme-machine');
INSERT INTO nomenclature (code, label) VALUES ('393', 'Techniques d’analyses chimiques');
INSERT INTO nomenclature (code, label) VALUES ('322', 'Télécoms / Antennes');
INSERT INTO nomenclature (code, label) VALUES ('438', 'Temps réels, lang.s synchrones, info. embatquée');
INSERT INTO nomenclature (code, label) VALUES ('205', 'Thermodynamique et physique de l’énergie');
INSERT INTO nomenclature (code, label) VALUES ('440', 'Trait. des connaissances et des sentiments');
INSERT INTO nomenclature (code, label) VALUES ('429', 'Traitement de l’image');
INSERT INTO nomenclature (code, label) VALUES ('440', 'Traitement des connaissances et des sentiments');
INSERT INTO nomenclature (code, label) VALUES ('486', 'Traitement du signal');
INSERT INTO nomenclature (code, label) VALUES ('575', 'Transport');
INSERT INTO nomenclature (code, label) VALUES ('510', 'Univers');
INSERT INTO nomenclature (code, label) VALUES ('528', 'Vieillissement, maladies génétiques');
INSERT INTO nomenclature (code, label) VALUES ('439', 'Vision artificielle, reconnaissance des formes');
INSERT INTO nomenclature (code, label) VALUES ('537', 'Xénobilogie, astrobiologie, origines de la vie');
